/**
 * Licensed to Apereo under one or more contributor license
 * agreements. See the NOTICE file distributed with this work
 * for additional information regarding copyright ownership.
 * Apereo licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file
 * except in compliance with the License.  You may obtain a
 * copy of the License at the following location:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */


/*
 * *** SSP TRAINING SET USER DATA INTO PLATFORM MSSQL Version***
 *
 * This SQL File sets user data into ssp-platform such that the user 
 * can login into the platform and have the abilities according to their SSP Role.
 *
 * It adds into tables up_person_dir, up_person_attr, up_person_attr_values, and SSP person among others.
 *
 * To use this file substitute the placeholders below via some other script
 *  or manually with the required data for each user adding a select statement each time. 
 *   This is a function so you would create a select statment for each new user. 
 *
 *  SELECT addUsersToPlatform('$(ENTEREDUSERNAME)','$(ENTEREDUSERPASSWORD)', '$(ENTEREDUSERFIRSTNAME)', '$(ENTEREDUSERLASTNAME)', '$(ENTEREDUSERUUID)', '$(ENTEREDUSERROLE), $(ENTEREDIS_MAP_TEMPLATE_ADMIN)';
 *
 * Substitute: 
 *	USERNAME = USERNAME of the new user to add (must be unique)
 *	USERPASSWORD = password of the new user to add 
 *		(must be generated by portalPasswordGenerator or uPortal and be in the SHA or MD5 form)
 *	USERFIRSTNAME = first name of the new user to add 
 *	USERLASTNAME = last name of the new user to add      
 *	USERUUID = the unique UUID that will be used by SSP for the new user (must be unique)
 *		Sample UUID: 7f000101-4159-1de6-8141-5b6b77c70013
 *                 (The SSP_STUDENT role doesn't use the UUID value)
 *      USERROLE = the SSP Role the user will have. These are shortened strings and valid values are:
 *                 STUDENT, COACH, FACULTY, MANAGER, SUPPORT, and DEVELOPER
 *                   (if it's a value different than the above, the user will be given the SSP_COACH role by default)
 *      IS_MAP_TEMPLATE_ADMIN = true 1/false 0 bit if the added user should be a MAP_TEMPLATE_ADMIN
 *                   
 * Note: Requires SQL Server 2008 or higher
 *
 */


--Function to Set Users in SSP-Platform for SSP TRAINING

IF object_id('addUsersToPlatform', 'p') IS NOT NULL
    exec ('DROP PROCEDURE addUsersToPlatform');

GO


CREATE PROCEDURE addUsersToPlatform @USERNAME VARCHAR(25), @PASSWORD VARCHAR(256), @FIRSTNAME VARCHAR(50), @LASTNAME VARCHAR(50), @UUID VARCHAR(36), @USERROLE VARCHAR(255), @IS_MAP_TEMPLATE_ADMIN VARCHAR(1)
AS

DECLARE @userDirId bigint;
DECLARE @userUserId bigint;
DECLARE @idAttr bigint; 
DECLARE @ifExists bit; 
DECLARE @blank integer; 
DECLARE @createdUUID uniqueidentifier; 
DECLARE @roleTitle varchar(16);
DECLARE @roleDepartment varchar(22);
DECLARE @sspRole varchar(19);
DECLARE @userEmail varchar(32);
DECLARE @userBirthdate date;
DECLARE @userStreetAddress varchar(17);
DECLARE @userAptAddress varchar(12);
DECLARE @userPhoneNumber varchar(16);
DECLARE @userBuilding varchar(16);
DECLARE @userOfficeHours varchar(15);
DECLARE @userDepartment varchar(18);
DECLARE @userRelationshipStatus varchar(10);
DECLARE @userPhotoUrl varchar(38);
DECLARE @throwAwayInt bigint; 
  

     --Delete can comment out for fresh database (NOTE: Need to delete students assigned/referenced first!)
      /* IF EXISTS(SELECT * FROM up_person_dir WHERE user_name = @USERNAME)
           DECLARE @temp bigint;
		   
	   BEGIN
               SET @temp = (SELECT TOP 1 id FROM up_person_attr WHERE user_dir_id = (SELECT user_dir_id FROM up_person_dir WHERE user_name = @USERNAME)  ORDER BY user_dir_id DESC);
               
               WHILE @temp IS NOT NULL		
               BEGIN			       
                     DELETE FROM up_person_attr_values WHERE attr_id = @temp;
                     DELETE FROM up_person_attr WHERE id = @temp;
	             SET @temp = (SELECT TOP 1 id FROM up_person_attr WHERE user_dir_id = (SELECT user_dir_id FROM up_person_dir WHERE user_name = @USERNAME)  ORDER BY user_dir_id DESC);
              END 
              DELETE FROM up_person_attr WHERE user_dir_id = (SELECT user_dir_id FROM up_person_dir WHERE user_name = @USERNAME);			   
              DELETE FROM up_person_dir WHERE user_name = @USERNAME;
	      DELETE FROM up_user WHERE user_name = @USERNAME;
              DELETE FROM person WHERE username = @USERNAME;  
	END; */
	--End Delete   
	
	 SET @createdUUID = (SELECT NEWID());	
         SET @userDirId = (SELECT next_val FROM UP_PERSON_DIR_SEQ) + 5;	
	 SET @idAttr = (SELECT next_val FROM UP_PERSON_ATTR_SEQ) + 5;
         SET @userUserId = (SELECT TOP 1 user_id FROM up_user ORDER BY user_id DESC) + 1;
	 
	 
	
      IF @USERROLE = 'STUDENT'
       BEGIN 
	 INSERT INTO up_person_dir(user_dir_id, entity_version, lst_pswd_cgh_dt, user_name, encrptd_pswd)
	 VALUES (@userDirId, '1', '2013-09-10 21:59:16.794', @USERNAME, @PASSWORD);

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES (@idAttr, '0', 'DATA_ACADEMIC_RESOURCE_CENTER', @userDirId);
 
         INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES (@idAttr, '_FALSE', '0'); 

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+5), '0', 'SSP_ROLES', @userDirId);

         INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+5), '_SSP_STUDENT', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+10), '0', 'sn', @userDirId);

	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+10), '_' + @LASTNAME, '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+15), '0', 'DATA_DISPLACED_WORKERS', @userDirId);

	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+15), '_FALSE', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+20), '0', 'DATA_FAST_FORWARD', @userDirId);

	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+20), '_FALSE', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+25), '0', 'DATA_DISABILITY', @userDirId);

	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+25), '_FALSE', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+30), '0', 'givenName', @userDirId);

  	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+30), '_' + @FIRSTNAME, '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+35), '0', 'DATA_INDIVIDUALIZED_LEARNING_PLAN', @userDirId);

 	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+35), '_FALSE', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+40), '0', 'DATA_EARLY_ALERT', @userDirId);

	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+40), '_FALSE', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+45), '0', 'DATA_ENGLISH_SECOND_LANGUAGE', @userDirId);

 	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+45), '_FALSE', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+50), '0', 'DATA_COUNSELING_SERVICES', @userDirId);

	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+50), '_FALSE', '0');
	
	 INSERT INTO up_user(user_id, user_name, user_dflt_usr_id, user_dflt_lay_id, next_struct_id, 
            lst_chan_updt_dt)
    	 VALUES (@userUserId, @USERNAME, 10, 1, 4, null);
        END	 
      ELSE	 
	BEGIN 
	
	SET @userEmail = 'demo'+@USERNAME+'@trainingssp.com';
	 
	 IF @USERROLE = 'FACULTY'
 	   BEGIN	
 		SET @roleTitle = '_Faculty';
 		SET @roleDepartment = '_Academic Faculty';
 		SET @sspRole = '_SSP_FACULTY';
 		SET @userBirthdate = '1960-07-07';
 		SET @userStreetAddress = '194 W. Demo St.';
 		SET @userAptAddress = 'Apt. 732';
 		SET @userPhoneNumber = '(555) 555-1209';
 		SET @userBuilding = 'South Building';
 		SET @userOfficeHours = 'M-W 1-5pm';
 		SET @userDepartment = 'Academic';
 		SET @userRelationshipStatus = 'Married';
 		SET @userPhotoUrl = '/ssp/images/demoAvatars/male_16.jpg';
 	   END
	 ELSE IF @USERROLE = 'MANAGER'
	   BEGIN
 		SET @roleTitle = '_Manager';
 		SET @roleDepartment = '_Advising Management';
 		SET @sspRole = '_SSP_MANAGER';
 		SET @userBirthdate = '1965-06-11';
 		SET @userStreetAddress = '253 W. Demo St.';
 		SET @userAptAddress = 'Apt. 456';
 		SET @userPhoneNumber = '(555) 555-4567';
 		SET @userBuilding = 'West Building';
 		SET @userOfficeHours = 'M-Th 10-4pm';
 		SET @userDepartment = 'Administration';
 		SET @userRelationshipStatus = 'Married';
 		SET @userPhotoUrl = '/ssp/images/demoAvatars/male_16.jpg';
 	   END
	 ELSE IF @USERROLE = 'SUPPORT'
 	   BEGIN	
 		SET @roleTitle = '_Staff';
 		SET @roleDepartment = '_Advising Staff';
 		SET @sspRole = '_SSP_SUPPORT_STAFF';
 		SET @userBirthdate = '1990-02-09';
 		SET @userStreetAddress = '834 W. Demo St.';
 		SET @userAptAddress = 'Apt. 123';
 		SET @userPhoneNumber = '(555) 555-1234';
 		SET @userBuilding = 'North Building';
 		SET @userOfficeHours = 'M-F 9-5pm';
 		SET @userDepartment = 'Advising Support';
 		SET @userRelationshipStatus = 'Single';
 		SET @userPhotoUrl = '/ssp/images/demoAvatars/male_16.jpg';
 	   END
	 ELSE IF @USERROLE = 'DEVELOPER'
	   BEGIN
 		SET @roleTitle = '_Developer';
 		SET @roleDepartment = '_IT Development';
 		SET @sspRole = '_SSP_DEVELOPER';
 		SET @userBirthdate = '1985-10-08';
 		SET @userStreetAddress = '789 W. Demo St.';
 		SET @userAptAddress = 'Apt. 886';
 		SET @userPhoneNumber = '(555) 555-9875';
 		SET @userBuilding = 'East Building';
 		SET @userOfficeHours = 'M-Sat 12am-12pm';
 		SET @userDepartment = 'IT Development';
 		SET @userRelationshipStatus = 'Single';
 		SET @userPhotoUrl = '/ssp/images/demoAvatars/male_16.jpg';
 	   END
	 ELSE
 	   BEGIN	
 	        SET @roleTitle = '_Senior Advisor';
 		SET @roleDepartment = '_Advising';
 		SET @sspRole = '_SSP_COACH';
 		SET @userBirthdate = '1970-05-05';
 		SET @userStreetAddress = '123 W. Demo St.';
 		SET @userAptAddress = 'Apt. 555';
 		SET @userPhoneNumber = '(555) 555-5555';
 		SET @userBuilding = 'North Building';
 		SET @userOfficeHours = 'M-Th 7-6pm';
 		SET @userDepartment = 'Advising';
 		SET @userRelationshipStatus = 'Married';
 		SET @userPhotoUrl = '/ssp/images/demoAvatars/male_04.jpg';
	   END ; 
 	 

	 INSERT INTO up_person_dir(user_dir_id, entity_version, lst_pswd_cgh_dt, user_name, encrptd_pswd)
	 VALUES (@userDirId, '1', '2013-09-10 21:59:16.794', @USERNAME, @PASSWORD);
	 	 
	 
         INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+5), '0', 'DATA_ACADEMIC_RESOURCE_CENTER', @userDirId);

         INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+5), '_TRUE', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+10), '0', 'SSP_ROLES', @userDirId);

	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+10), @sspRole, '0');
         
         IF @IS_MAP_TEMPLATE_ADMIN = 1
         BEGIN  
	      INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
              VALUES ((@idAttr+15), '_SSP_MAP_TEMPLATE_ADMIN', '0');
         END ; 

         INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+20), '0', 'mail', @userDirId);

	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+20), '_' + @userEmail, '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+25), '0', 'DATA_DISPLACED_WORKERS', @userDirId);

	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+25), '_TRUE', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+30), '0', 'sn', @userDirId);

         INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+30), '_' + @LASTNAME, '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+35), '0', 'alternateEmailAddress', @userDirId);

	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+35), '_' + @userEmail, '0');

         INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+40), '0', 'department', @userDirId);

         INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+40), @roleDepartment, '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+45), '0', 'DATA_FAST_FORWARD', @userDirId);

         INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+45), '_TRUE', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+50), '0', 'DATA_DISABILITY', @userDirId);

         INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+50), '_TRUE', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+55), '0', 'givenName', @userDirId);

         INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+55), '_' + @FIRSTNAME, '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+60), '0', 'DATA_INDIVIDUALIZED_LEARNING_PLAN', @userDirId);

 	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+60), '_TRUE', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+65), '0', 'DATA_EARLY_ALERT', @userDirId);

         INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+65), '_TRUE', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+70), '0', 'DATA_ENGLISH_SECOND_LANGUAGE', @userDirId);

	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+70), '_TRUE', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+75), '0', 'title', @userDirId);

 	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+75), @roleTitle, '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+80), '0', 'organization', @userDirId);

 	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+80), '_SSP Training', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+85), '0', 'DATA_COUNSELING_SERVICES', @userDirId);

         INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+85), '_TRUE', '0');

	 INSERT INTO up_person_attr(id, entity_version, attr_name, user_dir_id)
	 VALUES ((@idAttr+90), '0', 'telephoneNumber', @userDirId);

	 INSERT INTO up_person_attr_values(attr_id, attr_value, value_order)
         VALUES ((@idAttr+90), '_' + @userPhoneNumber, '0');

         
         INSERT INTO up_user(user_id, user_name, user_dflt_usr_id, user_dflt_lay_id, next_struct_id, lst_chan_updt_dt)
    	 VALUES (@userUserId, @USERNAME, 10, 1, 4, null);    	 
    	 
    	 
    	 INSERT INTO external_person(school_id, username, first_name, middle_name, last_name, birth_date, primary_email_address, address_line_1, address_line_2, city, state, zip_code, home_phone, work_phone, office_location, office_hours, department_name, actual_start_term, actual_start_year, marital_status, ethnicity, gender, is_local, balance_owed, coach_school_id, cell_phone, photo_url, residency_county, f1_status, non_local_address, student_type_code, race_code)
VALUES (@USERNAME, @USERNAME, @FIRSTNAME, 'M', @LASTNAME, @userBirthdate, @userEmail, @userStreetAddress, @userAptAddress, 'Phoenix', 'AZ','55555', @userPhoneNumber, @userPhoneNumber, @userBuilding, @userOfficeHours, @userDepartment, NULL, NULL, @userRelationshipStatus, 'Other', 'M', 't', NULL, NULL, @userPhoneNumber, @userPhotoUrl, 'DemoCounty', NULL, 'N', NULL, 'Other');

INSERT INTO person_staff_details(id, created_date, modified_date, created_by, modified_by, object_status, office_location, office_hours, department_name)
VALUES (@createdUUID, '2013-09-13 09:22:00.092', '2013-09-13 09:22:00.092', '58ba5ee3-734e-4ae9-b9c5-943774b4de41','58ba5ee3-734e-4ae9-b9c5-943774b4de41', '1', @userBuilding, @userOfficeHours, @userDepartment);

	 INSERT INTO person(id, first_name, middle_name, last_name, birth_date, primary_email_address, secondary_email_address, username, home_phone, work_phone, cell_phone, address_line_1, address_line_2, city, state, zip_code, photo_url, school_id, enabled, created_date, modified_date, created_by,modified_by, object_status, person_demographics_id, person_education_goal_id, person_education_plan_id, coach_id, ability_to_benefit, anticipated_start_term, anticipated_start_year, student_intake_request_date,student_type_id, student_intake_complete_date, person_staff_details_id,actual_start_year, actual_start_term, non_local_address, alternate_address_in_use,alternate_address_line_1, alternate_address_line_2, alternate_address_city,alternate_address_state, alternate_address_zip_code, alternate_address_country,person_disability_id, f1_status, residency_county, person_class,secret,oauth2_client_access_token_validity_seconds)
	 VALUES (@UUID, @FIRSTNAME, 'M', @LASTNAME, @userBirthdate, @userEmail, @userEmail, @USERNAME, @userPhoneNumber, @userPhoneNumber, @userPhoneNumber, @userStreetAddress, @userAptAddress, 'Phoenix', 'AZ','55555', @userPhotoUrl, @USERNAME, '1', '2010-08-20', '2010-08-20','58ba5ee3-734e-4ae9-b9c5-943774b4de41','58ba5ee3-734e-4ae9-b9c5-943774b4de41', '1', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, @createdUUID, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'DemoCounty', 'user', NULL, NULL);
	 
	 IF @USERROLE = 'COACH'
	 BEGIN
 		INSERT INTO early_alert_routing(id, created_date, modified_date, created_by, modified_by, object_status, campus_id, early_alert_reason_id, person_id, group_name, group_email)
VALUES ((SELECT NEWID()), '2013-09-13 09:22:00.092', '2013-09-13 09:22:00.092', '58ba5ee3-734e-4ae9-b9c5-943774b4de41','58ba5ee3-734e-4ae9-b9c5-943774b4de41', '1', (SELECT TOP 1 id FROM campus ORDER BY NEWID()), (SELECT TOP 1 id FROM early_alert_reason ORDER BY NEWID()), @UUID, 'Early Alert Routing Group '  +  @USERNAME, 'demo@trainingssp.com');

	 END ; 
      END ;          
      
         --Increment the sequences / Fixes error in ssp-platform admin on add/edit a user after data load 
         UPDATE UP_PERSON_DIR_SEQ SET next_val = (@userDirId + 20);	
	 UPDATE UP_PERSON_ATTR_SEQ SET next_val = (@idAttr+100);

GO

-- End Function


   EXEC addUsersToPlatform  @USERNAME="$(USERNAME)", @PASSWORD="$(USERPASSWORD)", @FIRSTNAME="$(USERFIRSTNAME)",  @LASTNAME="$(USERLASTNAME)", @UUID="$(USERUUID)", @USERROLE="$(USERROLE)", @IS_MAP_TEMPLATE_ADMIN="$(USER_IS_MAP_TEMPLATE_ADMIN)";

GO
   
--End Add Users to Platform Script
